apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assetservice
  template:
    metadata:
      labels:
        app: assetservice
    spec:
      containers:
        - name: assetservice
          image: matthijs1999/assetservice:latest