apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assetservice
  template:
    metadata:
      labels:
        app: assetservice
    spec:
      containers:
        - name: assetservice
          image: assetstoreregistry.azurecr.io/assetservice:v0.1
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: assets-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: assetservice
  ports:
  - name: assetservice
    protocol: TCP
    port: 80
    targetPort: 80