apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: matthijs1999/authenticatieservice:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-srv
spec:
  type: LoadBalancer
  selector:
    app: authservice
  ports:
  - name: authservice
    protocol: TCP
    port: 80
    targetPort: 80

    