apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-depl
  template:
    metadata:
      labels:
        app: users-depl
    spec:
      containers:
        - name: users-depl
          image: assetstoreregistry.azurecr.io/userservice:v0.1
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: users-depl
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: users-depl